version: "2.4"
networks:
  localdev:
    external: true  
services:  
  redis:
    image: redis:latest
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    restart: unless-stopped
    ports:
      - "${REDIS_TCP_PORT:-6379}:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - localdev